const { create } = require('xmlbuilder2');

function generate(stations, modules, ioPoints) {
  const sortedStations = [...stations].sort((a, b) => a.order - b.order);
  
  const root = create({ version: '1.0', encoding: 'UTF-8' })
    .ele('PLCopenXML', { 
      'xmlns': 'http://www.plcopen.org/xml/tc6_0201',
      'version': '2.0',
      'xmlns:xsi': 'http://www.w3.org/2001/XMLSchema-instance',
      'xsi:schemaLocation': 'http://www.plcopen.org/xml/tc6_0201 http://www.plcopen.org/xml/tc6_0201.xsd'
    });

  const header = root.ele('Header');
  header.ele('Vendor').txt('Trae');
  header.ele('ProductName').txt('PLCopenXML Generator');
  header.ele('ProductVersion').txt('1.0.0');
  header.ele('CreationDateTime').txt(new Date().toISOString());

  const project = root.ele('Project');
  project.ele('Name').txt('AutoGeneratedProject');
  project.ele('Description').txt('自动生成的PLC项目');

  const types = root.ele('Types');
  const dataTypes = types.ele('DataTypes');
  const functionBlocks = types.ele('FunctionBlocks');
  
  modules.forEach(module => {
    module.functionBlocks.forEach(fb => {
      const fbType = functionBlocks.ele('FunctionBlock', { 'name': fb.name, 'globalId': `FB_${fb.name}` });
      const interface = fbType.ele('Interface');
      
      if (fb.interface.inputs && fb.interface.inputs.length > 0) {
        const inputs = interface.ele('Inputs');
        fb.interface.inputs.forEach(input => {
          inputs.ele('Variable', { 'name': input.name, 'type': input.type });
        });
      }
      
      if (fb.interface.outputs && fb.interface.outputs.length > 0) {
        const outputs = interface.ele('Outputs');
        fb.interface.outputs.forEach(output => {
          outputs.ele('Variable', { 'name': output.name, 'type': output.type });
        });
      }
    });
  });

  const applications = root.ele('Applications');
  const application = applications.ele('Application', { 'name': 'MainApplication', 'resource': 'Resource1' });
  
  const programOrganization = application.ele('ProgramOrganization');
  
  sortedStations.forEach(station => {
    const stationFolder = programOrganization.ele('Folder', { 'name': station.name, 'globalId': `FOLDER_${station.id}` });
    
    station.modules.forEach(moduleId => {
      const module = modules.find(m => m.id === moduleId);
      if (module) {
        const moduleFolder = stationFolder.ele('Folder', { 'name': module.name, 'globalId': `FOLDER_${module.id}` });
        
        module.functionBlocks.forEach(fb => {
          const instanceName = `${module.name}_${fb.name}_${station.id}`;
          const fbInstance = moduleFolder.ele('FunctionBlockInstance', { 
            'name': instanceName, 
            'type': fb.name,
            'globalId': `FBINST_${instanceName}`
          });
        });
      }
    });
  });

  const data = application.ele('Data');
  const globalVars = data.ele('GlobalVariables');
  
  ioPoints.forEach(io => {
    const varType = getPlcType(io.type);
    globalVars.ele('Variable', {
      'name': io.name,
      'type': varType,
      'address': io.id,
      'accessType': 'readWrite'
    }).ele('Description').txt(io.description);
  });

  const taskConfiguration = application.ele('TaskConfiguration');
  const task = taskConfiguration.ele('Task', { 'name': 'MainTask', 'interval': '10ms', 'priority': '1' });
  task.ele('ProgramReference', { 'name': 'MainProgram' });

  return root.end({ prettyPrint: true });
}

function getPlcType(ioType) {
  const typeMap = {
    'DI': 'BOOL',
    'DO': 'BOOL',
    'AI': 'INT',
    'AO': 'INT',
    'I': 'BOOL',
    'Q': 'BOOL',
    'IW': 'INT',
    'QW': 'INT'
  };
  return typeMap[ioType] || 'BOOL';
}

module.exports = { generate };